import time
from natquery.llm.client import generate_sql
from natquery.execution.engine import execute_sql
from natquery.config.settings import Settings
from natquery.security.validator import validate_sql
from natquery.observability.logger import NatQueryLogger
from natquery.orchestration.error_handler import handle_query_error


def run_query(user_query: str):

    conv_id = NatQueryLogger.generate_conv_id()
    db_name = Settings.get_db_config()["dbname"]

    # -------- LOG INPUT --------
    NatQueryLogger.log_event(
        level="INFO",
        event="query_received",
        db_name=db_name,
        conv_id=conv_id,
        details={"user_query": user_query},
    )

    # -------- LLM STEP --------
    try:
        sql = generate_sql(user_query)

        if not sql or len(sql.strip()) == 0:
            raise ValueError("Empty SQL generated by LLM")

        NatQueryLogger.log_event(
            level="INFO",
            event="llm_sql_generated",
            db_name=db_name,
            conv_id=conv_id,
            details={"generated_sql": sql},
        )

    except Exception as e:
        NatQueryLogger.log_event(
            level="ERROR",
            event="llm_generation_failed",
            db_name=db_name,
            conv_id=conv_id,
            details={"error": str(e)},
        )
        raise

    # -------- VALIDATION --------
    try:
        validate_sql(sql)

    except Exception as e:

        NatQueryLogger.log_event(
            level="ERROR",
            event="sql_validation_failed",
            db_name=db_name,
            conv_id=conv_id,
            details={
                "error": str(e),
                "generated_sql": sql,
            },
        )

        # Attempt correction EVEN on validation failure
        sql = handle_query_error(
            user_query,
            sql,
            e,
            conv_id,
            db_name,
        )

    # -------- EXECUTION --------
    start_time = time.time()

    try:
        result = execute_sql(sql)

    except Exception as e:

        NatQueryLogger.log_event(
            level="ERROR",
            event="db_execution_failed",
            db_name=db_name,
            conv_id=conv_id,
            details={
                "error": str(e),
                "generated_sql": sql,
            },
        )

        # Self-correction loop
        sql = handle_query_error(
            user_query,
            sql,
            e,
            conv_id,
            db_name,
        )

        # Retry execution once corrected
        result = execute_sql(sql)

    # -------- SUCCESS LOGGING --------
    execution_time_ms = (time.time() - start_time) * 1000
    rows_returned = len(result)

    NatQueryLogger.log_event(
        level="INFO",
        event="db_execution_completed",
        db_name=db_name,
        conv_id=conv_id,
        details={
            "rows_returned": rows_returned,
            "execution_time_ms": execution_time_ms,
        },
    )

    NatQueryLogger.log_conversation(
        db_name=db_name,
        conv_id=conv_id,
        user_query=user_query,
        generated_sql=sql,
        rows_returned=rows_returned,
        execution_time_ms=execution_time_ms,
    )

    return result
